insert into tblStoreHistory values (seqStoreHistory.nextVal, 2, 52, '2021-04-27', 3, 'n');
insert into tblStoreHistory values (seqStoreHistory.nextVal, 3, 72, '2021-07-09', 4, 'n');
insert into tblStoreHistory values (seqStoreHistory.nextVal, 23, 24, '2021-07-06', 1, 'n');
insert into tblStoreHistory values (seqStoreHistory.nextVal, 15, 40, '2021-03-19', 7, 'n');
insert into tblStoreHistory values (seqStoreHistory.nextVal, 20, 83, '2021-05-15', 5, 'y');
insert into tblStoreHistory values (seqStoreHistory.nextVal, 12, 22, '2021-06-25', 8, 'y');
insert into tblStoreHistory values (seqStoreHistory.nextVal, 20, 94, '2021-05-08', 4, 'y');
insert into tblStoreHistory values (seqStoreHistory.nextVal, 2, 76, '2021-05-05', 5, 'n');
insert into tblStoreHistory values (seqStoreHistory.nextVal, 15, 2, '2021-01-16', 4, 'y');
insert into tblStoreHistory values (seqStoreHistory.nextVal, 1, 39, '2021-04-13', 5, 'n');
insert into tblStoreHistory values (seqStoreHistory.nextVal, 5, 1, '2021-01-22', 3, 'n');
insert into tblStoreHistory values (seqStoreHistory.nextVal, 22, 18, '2021-02-08', 1, 'n');
insert into tblStoreHistory values (seqStoreHistory.nextVal, 8, 81, '2021-02-17', 9, 'n');
insert into tblStoreHistory values (seqStoreHistory.nextVal, 20, 25, '2021-06-29', 1, 'y');
insert into tblStoreHistory values (seqStoreHistory.nextVal, 18, 42, '2021-06-05', 2, 'n');
insert into tblStoreHistory values (seqStoreHistory.nextVal, 7, 35, '2021-04-16', 6, 'n');
insert into tblStoreHistory values (seqStoreHistory.nextVal, 3, 52, '2021-04-29', 7, 'y');
insert into tblStoreHistory values (seqStoreHistory.nextVal, 18, 100, '2021-02-06', 8, 'y');
insert into tblStoreHistory values (seqStoreHistory.nextVal, 7, 25, '2021-01-29', 9, 'y');
insert into tblStoreHistory values (seqStoreHistory.nextVal, 20, 15, '2021-01-13', 9, 'n');



insert into tblCouponHave values(SeqcouponHave.nextVal, 82, 2 );
insert into tblCouponHave values(SeqcouponHave.nextVal, 87, 5 );
insert into tblCouponHave values(SeqcouponHave.nextVal, 19, 4 );
insert into tblCouponHave values(SeqcouponHave.nextVal, 81, 4 );
insert into tblCouponHave values(SeqcouponHave.nextVal, 9, 5 );
insert into tblCouponHave values(SeqcouponHave.nextVal, 26, 4 );
insert into tblCouponHave values(SeqcouponHave.nextVal, 29, 4 );
insert into tblCouponHave values(SeqcouponHave.nextVal, 80, 4 );
insert into tblCouponHave values(SeqcouponHave.nextVal, 88, 5 );
insert into tblCouponHave values(SeqcouponHave.nextVal, 23, 4 );
insert into tblCouponHave values(SeqcouponHave.nextVal, 54, 1 );
insert into tblCouponHave values(SeqcouponHave.nextVal, 72, 2 );
insert into tblCouponHave values(SeqcouponHave.nextVal, 37, 3 );
insert into tblCouponHave values(SeqcouponHave.nextVal, 86, 1 );
insert into tblCouponHave values(SeqcouponHave.nextVal, 31, 6 );
insert into tblCouponHave values(SeqcouponHave.nextVal, 34, 2 );
insert into tblCouponHave values(SeqcouponHave.nextVal, 34, 3 );
insert into tblCouponHave values(SeqcouponHave.nextVal, 55, 6 );
insert into tblCouponHave values(SeqcouponHave.nextVal, 56, 1 );
insert into tblCouponHave values(SeqcouponHave.nextVal, 26, 4 );
insert into tblCouponHave values(SeqcouponHave.nextVal, 100, 2 );
insert into tblCouponHave values(SeqcouponHave.nextVal, 35, 4 );
insert into tblCouponHave values(SeqcouponHave.nextVal, 59, 3 );
insert into tblCouponHave values(SeqcouponHave.nextVal, 86, 1 );
insert into tblCouponHave values(SeqcouponHave.nextVal, 15, 1 );
insert into tblCouponHave values(SeqcouponHave.nextVal, 58, 2 );
insert into tblCouponHave values(SeqcouponHave.nextVal, 1, 2 );
insert into tblCouponHave values(SeqcouponHave.nextVal, 14, 1 );
insert into tblCouponHave values(SeqcouponHave.nextVal, 37, 3 );
insert into tblCouponHave values(SeqcouponHave.nextVal, 49, 3 );
insert into tblCouponHave values(SeqcouponHave.nextVal, 11, 6 );
insert into tblCouponHave values(SeqcouponHave.nextVal, 65, 4 );
insert into tblCouponHave values(SeqcouponHave.nextVal, 60, 2 );
insert into tblCouponHave values(SeqcouponHave.nextVal, 100, 6 );
insert into tblCouponHave values(SeqcouponHave.nextVal, 96, 6 );
insert into tblCouponHave values(SeqcouponHave.nextVal, 66, 5 );
insert into tblCouponHave values(SeqcouponHave.nextVal, 93, 3 );
insert into tblCouponHave values(SeqcouponHave.nextVal, 46, 6 );
insert into tblCouponHave values(SeqcouponHave.nextVal, 86, 2 );
insert into tblCouponHave values(SeqcouponHave.nextVal, 94, 4 );
insert into tblCouponHave values(SeqcouponHave.nextVal, 93, 4 );
insert into tblCouponHave values(SeqcouponHave.nextVal, 31, 5 );
insert into tblCouponHave values(SeqcouponHave.nextVal, 12, 2 );
insert into tblCouponHave values(SeqcouponHave.nextVal, 88, 3 );
insert into tblCouponHave values(SeqcouponHave.nextVal, 66, 1 );
insert into tblCouponHave values(SeqcouponHave.nextVal, 20, 3 );
insert into tblCouponHave values(SeqcouponHave.nextVal, 3, 1 );
insert into tblCouponHave values(SeqcouponHave.nextVal, 28, 3 );
insert into tblCouponHave values(SeqcouponHave.nextVal, 72, 1 );
insert into tblCouponHave values(SeqcouponHave.nextVal, 65, 5 );

insert into tblCouponStatus values(seqCouponStatus.nextVal, '2021-07-09', 1);
insert into tblCouponStatus values(seqCouponStatus.nextVal, '2021-07-03', 2);
insert into tblCouponStatus values(seqCouponStatus.nextVal, '2021-07-26', 3);
insert into tblCouponStatus values(seqCouponStatus.nextVal, '2021-07-06', 4);
insert into tblCouponStatus values(seqCouponStatus.nextVal, '2021-07-04', 5);
insert into tblCouponStatus values(seqCouponStatus.nextVal, '2021-07-28', 6);
insert into tblCouponStatus values(seqCouponStatus.nextVal, '2021-07-14', 7);
insert into tblCouponStatus values(seqCouponStatus.nextVal, '2021-07-11', 8);
insert into tblCouponStatus values(seqCouponStatus.nextVal, '2021-07-24', 9);
insert into tblCouponStatus values(seqCouponStatus.nextVal, '2021-07-04', 10);
insert into tblCouponStatus values(seqCouponStatus.nextVal, '2021-07-16', 11);
insert into tblCouponStatus values(seqCouponStatus.nextVal, '2021-07-06', 12);
insert into tblCouponStatus values(seqCouponStatus.nextVal, '2021-07-08', 13);
insert into tblCouponStatus values(seqCouponStatus.nextVal, '2021-07-10', 14);
insert into tblCouponStatus values(seqCouponStatus.nextVal, '2021-07-08', 15);
insert into tblCouponStatus values(seqCouponStatus.nextVal, '2021-07-28', 16);
insert into tblCouponStatus values(seqCouponStatus.nextVal, '2021-07-18', 17);
insert into tblCouponStatus values(seqCouponStatus.nextVal, '2021-07-27', 18);
insert into tblCouponStatus values(seqCouponStatus.nextVal, '2021-07-01', 19);
insert into tblCouponStatus values(seqCouponStatus.nextVal, '2021-07-12', 20);
insert into tblCouponStatus values(seqCouponStatus.nextVal, '2021-07-22', 21);
insert into tblCouponStatus values(seqCouponStatus.nextVal, '2021-07-19', 22);
insert into tblCouponStatus values(seqCouponStatus.nextVal, '2021-07-03', 23);
insert into tblCouponStatus values(seqCouponStatus.nextVal, '2021-07-25', 24);
insert into tblCouponStatus values(seqCouponStatus.nextVal, '2021-07-23', 25);
insert into tblCouponStatus values(seqCouponStatus.nextVal, '2021-07-25', 26);
insert into tblCouponStatus values(seqCouponStatus.nextVal, '2021-07-25', 27);
insert into tblCouponStatus values(seqCouponStatus.nextVal, '2021-07-05', 28);
insert into tblCouponStatus values(seqCouponStatus.nextVal, '2021-07-20', 29);
insert into tblCouponStatus values(seqCouponStatus.nextVal, '2021-07-02', 30);
insert into tblCouponStatus values(seqCouponStatus.nextVal, '2021-07-11', 31);
insert into tblCouponStatus values(seqCouponStatus.nextVal, '2021-07-08', 32);
insert into tblCouponStatus values(seqCouponStatus.nextVal, '2021-07-11', 33);
insert into tblCouponStatus values(seqCouponStatus.nextVal, '2021-07-12', 34);
insert into tblCouponStatus values(seqCouponStatus.nextVal, '2021-07-28', 35);
insert into tblCouponStatus values(seqCouponStatus.nextVal, '2021-07-04', 36);
insert into tblCouponStatus values(seqCouponStatus.nextVal, '2021-07-21', 37);
insert into tblCouponStatus values(seqCouponStatus.nextVal, '2021-07-05', 38);
insert into tblCouponStatus values(seqCouponStatus.nextVal, '2021-07-24', 39);
insert into tblCouponStatus values(seqCouponStatus.nextVal, '2021-07-07', 40);
insert into tblCouponStatus values(seqCouponStatus.nextVal, '2021-07-17', 41);
insert into tblCouponStatus values(seqCouponStatus.nextVal, '2021-07-26', 42);
insert into tblCouponStatus values(seqCouponStatus.nextVal, '2021-07-20', 43);
insert into tblCouponStatus values(seqCouponStatus.nextVal, '2021-07-14', 44);
insert into tblCouponStatus values(seqCouponStatus.nextVal, '2021-07-15', 45);
insert into tblCouponStatus values(seqCouponStatus.nextVal, '2021-07-03', 46);
insert into tblCouponStatus values(seqCouponStatus.nextVal, '2021-07-30', 47);
insert into tblCouponStatus values(seqCouponStatus.nextVal, '2021-07-20', 48);
insert into tblCouponStatus values(seqCouponStatus.nextVal, '2021-07-18', 49);
insert into tblCouponStatus values(seqCouponStatus.nextVal, '2021-07-30', 50);

commit;